--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/BlockMagicDev/TradeNPC
build-by-default: true
branches:
- main
projects:
  TradeNPC:
    path: ""
    lint: false
    libs:
    - src: Muqsit/InvMenu/InvMenu
      version: ^4.3.4
...
